[build]
  functions = "functions"
[dev]
  functions = "functions"
  publish = "public"
  
[functions]
  included_files = ["node_modules/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
